---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h0m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
