---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 6.2.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    provider: cloudflare
    cloudflare:
      apiToken: "${CLOUDFLARE_API_TOKEN}"
      email: "${CLOUDFLARE_EMAIL}"
      proxied: true
    txtOwnerId: "${ENVIRONMENT}-external-dns"
    domainFilters:
      - "${DOMAIN}"
    sources:
      - istio-virtualservice
