---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./operators/minikube
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
#  postBuild:
#    substitute: {}
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-secrets
