---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    config:
      clientID: ${OAUTH2_PROXY_CLIENT_ID}
      clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
      cookieSecret: ${OAUTH2_PROXY_COOKIE_SECRET}
    extraArgs:
      provider: github
      cookie-expire: 2h
      cookie-refresh: 1h
      set-xauthrequest: true
      reverse-proxy: true
      set-authorization-header: true
      pass-authorization-header: true
      pass-user-headers: true
      pass-host-header: true
      pass-access-token: true
      upstream: "static://200"
